[tool.black]
line-length = 120
preview = true

[tool.isort]
profile = "black"
known_absolute = "sentinelhub"
known_local_folder = "utils"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "ABSOLUTE", "LOCALFOLDER"]
line_length = 120

[tool.nbqa.addopts]
flake8 = [
    "--extend-ignore=E402,E501"
]
